### ISSUE TITLE
tsconfig.json error

### ISSUE THREAD

**Issue by shawnmitchell** [DougAnderson444/solblog#2]
```
Cannot write file '[Path...]/solblog/app/src/lib/anchorClient.js' because it would overwrite input file.
```
is the error.

This is from a clean clone of the repo. Just ran `yarn` in the base project directory and then `yarn` in `./app`

Any idea how to fix? Thanks in advance and thanks for making this tutorial!

**Comment by DougAnderson444** [comment]
Hmm, strange first I have seen of this. I did use `npm` vice `yarn` but I doubt that makes a difference. 

I checked the repo and noticed there is no `svelte2tsx` in the `package.json` (sometime when adding pkgs on the fly in Vite is just caches them in Vite)

Can you try 

```
cd ./app
yarn svelte2tsx
```

**Comment by DougAnderson444** [comment]
I also know that the sveltekit site uses `npm`, again I haven't tried it with yarn so I'm unsure if it causes problems or not. 

```
npm init svelte@next my-app
cd my-app
npm install
npm run dev -- --open
```
